spring.application.name=cleard

server.address=127.0.0.1
server.port=0

spring.datasource.url=jdbc:sqlite:${user.home}/.cleard/cleard.db?journal_mode=WAL&busy_timeout=5000&foreign_keys=true
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

logging.file.name=${user.home}/.cleard/cleard.log
